### ISSUE TITLE
Can't execute after installing with pip

### ISSUE THREAD

**Issue by nremond** [gforcada/haproxy_log_analysis#7]
I installed `haproxy_log_analysis` with `pip` on Ubuntu 14.04.
But, after that, I can't execute the program: 
```
nicolas@lb01:/var/log# haproxy_log_analysis
Traceback (most recent call last):
  File "/usr/local/bin/haproxy_log_analysis", line 9, in <module>
    load_entry_point('haproxy-log-analysis==0.0.3', 'console_scripts', 'haproxy_log_analysis')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/haproxy/main.py", line 3, in <module>
    from haproxy import DELTA_REGEX
ImportError: cannot import name DELTA_REGEX
```

If I look at what got installed, I can see that the `__init__.py`file is missing, but it seems bizarre that the `test` folder is present: 

```
nicolas@lb01:/var/log# ls /usr/local/lib/python2.7/dist-packages/haproxy/
filters.py  filters.pyc  haproxy_logfile.py  haproxy_logfile.pyc  haproxy_logline.py  haproxy_logline.pyc  main.py  main.pyc  tests
```

Best,
Nicolas

**Comment by gforcada** [comment]
Finally fixed it!

Again, thanks for reporting.

Version 0.0.3.post2 should be working.
